### ISSUE TITLE
TAB v6.1.1 doesn't work with 1.8.8

### ISSUE THREAD

**Issue by Jan1598** [NEZNAMY/TAB#1706]
### Server version

Pandaspigot 1.8.8

### TAB version

6.1.1

### Plugin list

ViaVersion, DecentHolograms, GrimAC

### Describe the bug

The TAB list is Vanilla and the Command for TAB doesn't work. But the plugin is loaded.
For newer Versions (1.21.11+) it works

### Expected behavior

The plugin work (like v6.1.0) for 1.8.8 Versions

### Steps to reproduce

Use PandaSpigot 1.8.8 and start the server

### Additional info

[23:06:38 INFO]: [TAB] [WARN] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[23:06:38 INFO]: [TAB] [WARN] java.lang.NoClassDefFoundError: Could not initialize class me.neznamy.tab.platforms.bukkit.BukkitTabPlayer
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.loadPlayers(BukkitPlatform.java:123)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.shared.TAB.load(TAB.java:203)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:24)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:49)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:35)
[23:06:38 INFO]: [TAB] [WARN]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:06:38 INFO]: [TAB] [WARN]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[23:06:38 INFO]: [TAB] [WARN]   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:700)
[23:06:38 INFO]: [TAB] [WARN]   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:663)
[23:06:38 INFO]: [TAB] [WARN]   at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:450)
[23:06:38 INFO]: [TAB] [WARN]   at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:413)
[23:06:38 INFO]: [TAB] [WARN]   at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:760)
[23:06:38 INFO]: [TAB] [WARN]   at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:649)
[23:06:38 INFO]: [TAB] [WARN]   at java.base/java.lang.Thread.run(Thread.java:1474)
[23:06:38 INFO]: [TAB] [WARN] Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute [in thread "TAB Processing Thread"]
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.<clinit>(BukkitTabPlayer.java:27)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.platforms.bukkit.BukkitEventListener.createPlayer(BukkitEventListener.java:66)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.platforms.bukkit.BukkitEventListener.createPlayer(BukkitEventListener.java:20)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:29)
[23:06:38 INFO]: [TAB] [WARN]   at me.neznamy.tab.shared.cpu.CaughtTask.run(CaughtTask.java:18)
[23:06:38 INFO]: [TAB] [WARN]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
[23:06:38 INFO]: [TAB] [WARN]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
[23:06:38 INFO]: [TAB] [WARN]   at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:309)
[23:06:38 INFO]: [TAB] [WARN]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[23:06:38 INFO]: [TAB] [WARN]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[23:06:38 INFO]: [TAB] [WARN]   at java.base/java.lang.Thread.run(Thread.java:1474)
[23:06:38 INFO]: [TAB] Failed to enable due to an internal plugin error. Check console for more info.

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Thanks for the report, hotfix 6.1.2 has been released.
